fix initialization of repos on new hosts

diff --git a/libexec/initrepos b/libexec/initrepos
--- a/libexec/initrepos
+++ b/libexec/initrepos
@@ -41,65 +41,74 @@ for HOSTREPO in `sed -n 's/^hostrepo\s*//p' /etc/cvmfs-user-pub.conf`; do
         MYREPO=false
     fi
 
-    if [ -d /srv/cvmfs/$REPO ]; then
-        # data previously existed, save it to re-use
-        if [ -d /srv/cvmfs/.$REPO.SAV ]; then
-            echo "Refusing to overwrite saved data, skipping $REPO"
-            continue
-        fi
-        echo "Saving /srv/cvmfs/$REPO in /srv/cvfs/.$REPO.SAV"
-        mv /srv/cvmfs/$REPO /srv/cvmfs/.$REPO.SAV
-    fi
-
-    REPOPUB=/etc/cvmfs/keys/$REPO.pub
-    DOMAIN="`echo $REPO|cut -d. -f2-`"
-    if [ ! -f $REPOPUB ]; then
-        REPOPUB=""
-    fi
-    PUB=/etc/cvmfs/keys/$DOMAIN.pub
-    if [ ! -f $PUB ]; then
-        PUB=/etc/cvmfs/keys/$DOMAIN/$DOMAIN.pub
-        if [ ! -f $PUB ]; then
-            if [ -z "$REPOPUB" ]; then
-                echo "No key found for $REPO"
-                continue
-            fi
-            PUB=""
-        fi
-    fi
-    if [ -n "$REPOPUB" ] && [ -n "$PUB" ]; then
-        PUB=":$PUB"
-    fi
-    PUB="$REPOPUB$PUB"
-    ADDEDONE=true
-
     if [ $MYREPO ]; then
         REPHOST=$OTHERHOST
     else
         REPHOST=$HOST
     fi
-    echo "Adding replica $REPO from $REPHOST"
-    if ! cvmfs_server add-replica -o cvmfspub http://$REPHOST/cvmfs/$REPO $PUB; then
-        echo "Failed to add-replica $REPO from $REPHOST with key $PUB"
-        if ! $MYREPO; then
-            continue
+    if [ -n "$REPHOST" ]; then
+        # bootstrap from the other host
+
+        if [ -d /srv/cvmfs/$REPO ]; then
+            # data previously existed, save it to re-use
+            if [ -d /srv/cvmfs/.$REPO.SAV ]; then
+                echo "Refusing to overwrite saved data, skipping $REPO"
+                continue
+            fi
+            echo "Saving /srv/cvmfs/$REPO in /srv/cvmfs/.$REPO.SAV"
+            mv /srv/cvmfs/$REPO /srv/cvmfs/.$REPO.SAV
         fi
-        # make sure that the repo really doesn't exist on the other host
-        #  so as to not overwrite it if it failed for another reason
-        if curl -sf http://$REPHOST/cvmfs/$REPO/.cvmfswhitelist >/dev/null; then
-            echo "Source repo does appear to exist on $REPHOST, so skipping"
-            continue
+
+        REPOPUB=/etc/cvmfs/keys/$REPO.pub
+        DOMAIN="`echo $REPO|cut -d. -f2-`"
+        if [ ! -f $REPOPUB ]; then
+            REPOPUB=""
         fi
-    fi
-    if [ -d /srv/cvmfs/.$REPO.SAV ]; then
-        echo "Restoring /srv/cvmfs/$REPO from /srv/cvfs/.$REPO.SAV"
-        rm -rf /srv/cvmfs/$REPO
-        mv /srv/cvmfs/.$REPO.SAV /srv/cvmfs/$REPO
-    fi
-    if ! cvmfs_server snapshot $REPO; then
-        echo "Failed to make initial snapshot of $REPO from $REPHOST"
-        if ! $MYREPO; then
-            continue
+        PUB=/etc/cvmfs/keys/$DOMAIN.pub
+        if [ ! -f $PUB ]; then
+            PUB=/etc/cvmfs/keys/$DOMAIN/$DOMAIN.pub
+            if [ ! -f $PUB ]; then
+                if [ -z "$REPOPUB" ]; then
+                    if ! $MYREPO; then
+                        echo "No key found for $REPO"
+                        continue
+                    fi
+                    echo "No key was found for $REPO, so creating from scratch"
+                fi
+                PUB=""
+            fi
+        fi
+        if [ -n "$REPOPUB" ] && [ -n "$PUB" ]; then
+            PUB=":$PUB"
+        fi
+        PUB="$REPOPUB$PUB"
+        ADDEDONE=true
+
+        if [ -n "$PUB" ]; then
+            echo "Adding replica $REPO from $REPHOST"
+            if ! cvmfs_server add-replica -o cvmfspub http://$REPHOST/cvmfs/$REPO $PUB; then
+                echo "Failed to add-replica $REPO from $REPHOST with key $PUB"
+                if ! $MYREPO; then
+                    continue
+                fi
+                # make sure that the repo really doesn't exist on the other host
+                #  so as to not overwrite it if it failed for another reason
+                if curl -sf http://$REPHOST/cvmfs/$REPO/.cvmfswhitelist >/dev/null; then
+                    echo "Source repo does appear to exist on $REPHOST, so skipping"
+                    continue
+                fi
+            fi
+        fi
+        if [ -d /srv/cvmfs/.$REPO.SAV ]; then
+            echo "Restoring /srv/cvmfs/$REPO from /srv/cvmfs/.$REPO.SAV"
+            rm -rf /srv/cvmfs/$REPO
+            mv /srv/cvmfs/.$REPO.SAV /srv/cvmfs/$REPO
+        fi
+        if [ -n "$PUB" ] && ! cvmfs_server snapshot $REPO; then
+            echo "Failed to make initial snapshot of $REPO from $REPHOST"
+            if ! $MYREPO; then
+                continue
+            fi
         fi
     fi
 
